### ISSUE TITLE
As soon as I enable the plugin my site crashes with error "Undefined variable: up_color"

### ISSUE THREAD

**Issue by mn113** [iusvar/grav-plugin-thumb-ratings#3]
After I click the color pickers in the plugin options in the admin dashboard, it works. It seems the colors were not initialised with a value.

**Comment by iusvar** [comment]
It is true, I have done but I have yet to release the fixes. In the meantime, you can add in the `thumb-ratings.yaml` file:

```yaml
up_bgcolor: '#00FF00'
down_bgcolor: '#FF0000'
up_color: '#ffffff'
down_color: '#ffffff'
```
